### ISSUE TITLE
Too much error when run app

### ISSUE THREAD

**Issue by nowfalsalahudeen** [macedigital/vuejs-starterkit#2]
✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\store\persistedState.js:15:39
      return !type.startsWith('route/');
                                         ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\store\persistedState.js:16:5
    },
       ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\store\persistedState.js:17:26
    storage: cookieStorage,
                            ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\store\persistedState.js:18:3
  };
     ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\store\persistedState.js:19:1

   ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\store\persistedState.js:20:59
  export default createPersistedState(persistedStateConfig);
                                                             ^

✘ 20 problems (20 errors, 0 warnings)

**Comment by macedigital** [comment]
@nowfalsalahudeen Thanks for your issue report. Looks like you're using Windows and haven't configured how to handle line-endings for cross-platform development, yet.

I guess, you clicked passed this screen with the setting "Checkout Windows-Style":

![windows-line-endings-fs8](https://user-images.githubusercontent.com/248495/37555856-74c7577e-29ee-11e8-971b-b24bc403a9a6.png)

For this, and *many, many other projects on github*, you should change the setting to 'as-is, but convert to LF on commit"-style.

You will encounter related issues time and time again, so it makes sense to apply the advice from [dealing-with-line-endings](https://help.github.com/articles/dealing-with-line-endings/#platform-windows) on your computer.

Commit 65cdb4ed2100d2cf63266e7772568cccc77ef1e3 added a `.gitattributes` file that forces LF line-endings even on Windows (regardless of settings).

In order to pick it up for the code you cloned from github, do a Google search on how to re-index your local checkout (also understand that settings in your editor may affect line-endings). 

Otherwise, just repeat and checkout a fresh copy of this repository and you'll notice that those false positives are gone.

Maybe you want to read more about [line-endings](https://en.wikipedia.org/wiki/Newline).
